services:
  php-app:
    container_name: php-app
    image: ivsslabcr.azurecr.io/ivss/php-app:prod
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      - user_uploads:/var/www/html/public/uploads
    networks:
    - ivss-network
    depends_on:
      - postgres-db
  
  postgres-db:
    container_name: postgres-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: db_ivss 
      POSTGRES_USER: ivss_user
      POSTGRES_PASSWORD: hB&4ySg9^rT*JzX%
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - ivss-network
  
  nginx:
    container_name: nginx-app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
    - ivss-network
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101
    depends_on:
      - php-app

volumes:
  postgres_data:
  user_uploads:

networks:
  ivss-network:
    external: true